apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-tqyhdzbe
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-tqyhdzbe:51899866ded96f196c1ab6f278ece9892394ea48@sha256:c2cd43f4ffb14d4573e3f0d4701e4dbe39b2cc010c2131589ec7234644dde428
          name: container-image
